apiVersion: v2
name: nifi
description: Ultimate Nifi helm chart
maintainers:
  - name: Antony Aleksandrov
    email: af.alexsandrov@gmail.com

home: https://nifi.apache.org/
sources:
  - https://github.com/apache/nifi
icon: https://nifi.apache.org/images/apache-nifi-drop-logo.svg
keywords:
  - apache
  - nifi
  - streaming
dependencies:
  - name: zookeeper
    version: 13.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: redis
    version: 20.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: postgresql
    version: 16.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

type: application

appVersion: "2.0.0"

version: 0.1.0