apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-config-map
data:
  NIFI_ANALYTICS_PREDICT_ENABLED: "true"
  NIFI_CLUSTER_IS_NODE: "false"
  NIFI_CLUSTER_NODE_CONNECTION_TIMEOUT: "2 min"
  NIFI_CLUSTER_PROTOCOL_CONNECTION_HANDSHAKE_TIMEOUT: "2 min"
  NIFI_CLUSTER_NODE_PROTOCOL_MAX_THREADS: "15"
  NIFI_CLUSTER_NODE_ADDRESS: "0.0.0.0"
  NIFI_CLUSTER_NODE_PROTOCOL_PORT: "8082"
  NIFI_CLUSTER_NODE_READ_TIMEOUT: "2 min"
  NIFI_ELECTION_MAX_CANDIDATES: "2"
  NIFI_ELECTION_MAX_WAIT: "1 min"
  NIFI_SENSITIVE_PROPS_KEY: "th1s1s3up34e5r37"
  NIFI_WEB_HTTP_HOST: "0.0.0.0"
  NIFI_WEB_HTTP_PORT: "8080"
  NIFI_FLOW_CONFIGURATION_ARCHIVE_ENABLED: "true"
  HADOOP_USER_NAME: "nifi"
  NIFI_ALLOW_EXPLICIT_KEYTAB: "true"
  {{- with .Values.extraConf }}
   {{- toYaml . | nindent 2 }}
  {{- end }}