apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-registry
  labels:
    {{.Release.Name }}-registry
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{.Release.Name }}-registry
